const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'tools/prosemirror-bundle/package.json'), 'utf8'));
const entry = fs.readFileSync(path.join(root, 'tools/prosemirror-bundle/prosemirror-entry.js'), 'utf8');
const adapter = fs.readFileSync(path.join(root, 'static_src/js/yolomux/93_prosemirror_editor.js'), 'utf8');

assert.equal(manifest.dependencies['prosemirror-markdown'], '1.13.7');
assert.equal(manifest.dependencies['prosemirror-model'], '1.25.11');
assert.equal(manifest.dependencies['prosemirror-history'], '1.5.0');
assert.equal(manifest.dependencies['prosemirror-state'], '1.4.4');
assert.equal(manifest.dependencies['prosemirror-view'], '1.42.3');
assert.match(entry, /window\.YOLOmuxProseMirror/);
assert.match(adapter, /function createProseMirrorPanel/);
assert.match(adapter, /function syncProseMirrorPanelSource/);
assert.match(adapter, /handleFileEditorContentChanged/);
assert.match(adapter, /MarkdownParser/);
assert.match(adapter, /PROSEMIRROR_SERIALIZE_DELAY_MS = 1250/);
assert.match(adapter, /'Shift-Enter': insertProseMirrorHardBreak\(api, schema\)/);
assert.doesNotMatch(adapter, /Enter: insertProseMirror/);
assert.match(adapter, /function scheduleProseMirrorAutosave/);
assert.match(adapter, /deferAutosave: true/);
assert.match(adapter, /disposeMarkdownPreviewEditing\(parts\.previewPane\)/);
assert.match(adapter, /setTimeout\(\(\) =>/);
assert.match(adapter, /syncCodeMirrorDocument/);
assert.match(adapter, /TextSelection\.create/);
assert.match(adapter, /soft_break/);
assert.match(adapter, /skipPreviewPanel/);
assert.match(adapter, /flushProseMirrorSource/);
assert.match(adapter, /api\.history\(\)/);
assert.match(adapter, /syncProseMirrorPanelSource[\s\S]*clearTimeout\(panel\._pmSerializeTimer\)/);
assert.match(adapter, /normalizeProseMirrorEndBreakSource/);
assert.match(adapter, /normalizeLegacyBreakMarkup/);
assert.match(adapter, /sourceSurface: 'view-editor'/);
assert.match(adapter, /prosemirrorSelectionAtClientPoint/);
assert.match(adapter, /prosemirrorSelectionHasMark/);
assert.match(adapter, /marks\.strike/);
assert.match(adapter, /marks\.underline/);
assert.match(adapter, /strike: \{open: '~~'/);
assert.match(adapter, /underline: \{open: '<u>'/);
assert.match(adapter, /s: \{mark: 'strike'\}/);
assert.match(adapter, /const markName = \{u: 'underline', mark: 'highlight', kbd: 'kbd', sup: 'superscript'\}/);
assert.match(adapter, /sup: 'superscript'/);
assert.match(adapter, /superscript: \{mark: 'superscript'\}/);
assert.match(adapter, /underline: \{mark: 'underline'\}/);
assert.match(adapter, /html_break: \{node: 'hard_break'\}/);
assert.match(adapter, /html_image: \{node: 'image'/);
assert.match(adapter, /details: \{block: 'details'/);
assert.match(adapter, /table: \{block: 'table'\}/);
assert.match(adapter, /tr: \{block: 'table_row'\}/);
assert.match(adapter, /th: \{block: 'table_header'/);
assert.match(adapter, /td: \{block: 'table_cell'/);
assert.match(adapter, /highlight: \{mark: 'highlight'\}/);
assert.match(adapter, /kbd: \{mark: 'kbd'\}/);
assert.match(adapter, /details\(state, node\)/);
assert.match(adapter, /function prosemirrorDetailsNodeView/);
assert.match(adapter, /function prosemirrorImageNodeView/);
assert.match(adapter, /markdown-it collapses extra blank lines/);
assert.match(adapter, /emptyParagraphs = Math\.max\(0, blockStart - previousBlockEnd - 1\)/);
assert.match(adapter, /trailingEmptyParagraphs = Math\.max\(0, trailingNewlines - 1\)/);
assert.match(adapter, /\['span', \{'data-markdown-soft-break': 'true'\}, ' '\]/);
assert.match(adapter, /paragraph\(state, node\)[\s\S]*state\.flushClose\(1\)/);
assert.match(adapter, /markdownPreviewImageTarget\(original, markdownPath\)/);
assert.match(adapter, /installRawFileMediaSource\(image, target\.path/);
assert.match(adapter, /image: node => prosemirrorImageNodeView\(node, panel, path\)/);
assert.match(adapter, /table\(state, node\)/);
assert.match(adapter, /details: prosemirrorDetailsNodeView/);
assert.match(adapter, /Unsupported raw HTML at line \$\{first\.line\}: \$\{first\.html\}/);
assert.match(adapter, /Markdown comments are authoring metadata, not editable document content/);
assert.match(adapter, /token\.type === 'html_inline' \|\| token\.type === 'html_block'/);
assert.doesNotMatch(adapter, /s_open: \{mark: 'strike'\}/);
assert.doesNotMatch(adapter, /html_inline: \{mark: 'underline'\}/);
assert.match(adapter, /const doc = parser\.parse\(state\.content \|\| ''\);[\s\S]*parts\.previewPane\.replaceChildren\(container\);[\s\S]*new api\.EditorView/);
assert.match(adapter, /function renderProseMirrorFailure/);
assert.match(adapter, /statusErr\(esc\(message\)\)/);
assert.doesNotMatch(adapter, /keeping Markdown Preview/);

console.log('prosemirror editor suite: 5 passed, 0 failed');
