#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 Keiven Chang. All rights reserved.
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
"""Generate YO!chat's lazy emoji search catalog from pinned Unicode CLDR data."""

from __future__ import annotations

import argparse
import json
import urllib.request
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "static_src" / "js" / "emoji" / "emoji_data.js"
CLDR_VERSION = "47.0.0"
UNICODE_EMOJI_VERSION = "16.0"
LOCALES = {
    "ar": "ar", "de": "de", "en": "en", "es": "es", "fr": "fr", "he": "he", "hi": "hi",
    "it": "it", "ja": "ja", "ko": "ko", "nl": "nl", "pl": "pl", "pt-BR": "pt", "ru": "ru",
    "th": "th", "tr": "tr", "vi": "vi", "zh-Hans": "zh", "zh-Hant": "zh-Hant",
}


def fetch_json(url: str) -> dict:
    with urllib.request.urlopen(url, timeout=60) as response:
        return json.load(response)


def fetch_text(url: str) -> str:
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read().decode("utf-8")


def emoji_sequence(text: str) -> list[tuple[str, str]]:
    result: list[tuple[str, str]] = []
    seen: set[str] = set()
    category = "symbols"
    for line in text.splitlines():
        if line.startswith("# group:"):
            category = line.partition(":")[2].strip().casefold().replace(" & ", "-").replace(" ", "-")
            continue
        data, separator, description = line.partition("#")
        if not separator or "; fully-qualified" not in data:
            continue
        glyph = description.strip().split(maxsplit=1)[0]
        if glyph and glyph not in seen:
            seen.add(glyph)
            result.append((glyph, category))
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    args = parser.parse_args()
    emoji_test = fetch_text(f"https://www.unicode.org/Public/emoji/{UNICODE_EMOJI_VERSION}/emoji-test.txt")
    glyphs = emoji_sequence(emoji_test)
    annotations: dict[str, dict] = {}
    for app_locale, cldr_locale in LOCALES.items():
        url = (
            f"https://raw.githubusercontent.com/unicode-org/cldr-json/{CLDR_VERSION}/"
            f"cldr-json/cldr-annotations-full/annotations/{cldr_locale}/annotations.json"
        )
        derived_url = (
            f"https://raw.githubusercontent.com/unicode-org/cldr-json/{CLDR_VERSION}/"
            f"cldr-json/cldr-annotations-derived-full/annotationsDerived/{cldr_locale}/annotations.json"
        )
        annotations[app_locale] = {
            **fetch_json(url)["annotations"]["annotations"],
            **fetch_json(derived_url)["annotationsDerived"]["annotations"],
        }
    records = []
    for glyph, category in glyphs:
        names: dict[str, str] = {}
        keywords: dict[str, list[str]] = {}
        for locale, catalog in annotations.items():
            entry = catalog.get(glyph) or catalog.get(glyph.replace("\ufe0f", ""))
            if not isinstance(entry, dict):
                continue
            tts = entry.get("tts")
            default = entry.get("default")
            if isinstance(tts, list) and tts:
                names[locale] = str(tts[0])
            if isinstance(default, list):
                keywords[locale] = [str(value) for value in default]
        if "en" in names:
            records.append({"emoji": glyph, "category": category, "names": names, "keywords": keywords})
    text = (
        f"// Generated by tools/build_emoji_catalog.py from Unicode Emoji {UNICODE_EMOJI_VERSION} and CLDR {CLDR_VERSION}.\n"
        "// Unicode data license: https://www.unicode.org/license.txt\n"
        f"globalThis.YOLOMUX_EMOJI_DATA = {json.dumps(records, ensure_ascii=False, separators=(',', ':'))};\n"
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(f"wrote {len(records)} emoji records to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
