# SPDX-FileCopyrightText: Copyright (c) 2026 Keiven Chang. All rights reserved.
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
"""Build served YOLOmux static assets from ordered source partials."""

from __future__ import annotations

import argparse
from collections import defaultdict
import json
import re
import sys
import time
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]

# i18n: source catalogs live in static_src/locales/<locale>.json; en.json is the source of truth.
# The build copies them to static/locales/ (all-static-fetch delivery), validates key parity, and
# generates the en-XA pseudo-locale (accented + padded) to surface unextracted strings + overflow.
LOCALES_SRC = REPO_ROOT / "static_src" / "locales"
LOCALES_OUT = REPO_ROOT / "static" / "locales"
SOURCE_LOCALE = "en"
PSEUDO_LOCALE = "en-XA"
_PSEUDO_ACCENTS = str.maketrans({
    "a": "á", "b": "ƀ", "c": "ç", "d": "đ", "e": "é", "f": "ƒ", "g": "ǧ", "h": "ĥ", "i": "í",
    "j": "ĵ", "k": "ķ", "l": "ł", "m": "ɱ", "n": "ñ", "o": "ó", "p": "ƥ", "q": "ɋ", "r": "ř",
    "s": "š", "t": "ť", "u": "ú", "v": "ṽ", "w": "ŵ", "x": "ẋ", "y": "ý", "z": "ž",
    "A": "Á", "B": "Ɓ", "C": "Ç", "D": "Đ", "E": "É", "F": "Ƒ", "G": "Ǧ", "H": "Ĥ", "I": "Í",
    "J": "Ĵ", "K": "Ķ", "L": "Ł", "M": "Ɱ", "N": "Ñ", "O": "Ó", "P": "Ƥ", "Q": "Ɋ", "R": "Ř",
    "S": "Š", "T": "Ť", "U": "Ú", "V": "Ṽ", "W": "Ŵ", "X": "Ẋ", "Y": "Ý", "Z": "Ž",
})

ASSETS: dict[str, list[str]] = {
    "yolomux.js": [
        "static_src/js/yolomux/00_bootstrap_state.js",
        "static_src/js/yolomux/05_i18n.js",
        "static_src/js/yolomux/10_core_utils.js",
        "static_src/js/yolomux/20_layout_state.js",
        "static_src/js/yolomux/30_app_menus.js",
        "static_src/js/yolomux/40_file_explorer_files.js",
        "static_src/js/yolomux/45_file_explorer_actions.js",
        "static_src/js/yolomux/50_editor_settings_runtime.js",
        "static_src/js/yolomux/60_popovers_tabs.js",
        "static_src/js/yolomux/70_layout_actions.js",
        "static_src/js/yolomux/75_dockview_layout.js",
        "static_src/js/yolomux/80_panes_preferences.js",
        "static_src/js/yolomux/90_changes_editor.js",
        "static_src/js/yolomux/95_codemirror_editor.js",
        "static_src/js/yolomux/99_terminal_boot.js",
    ],
    "yolomux.css": [
        "static_src/css/yolomux/00_tokens_base.css",
        "static_src/css/yolomux/10_topbar_menus.css",
        "static_src/css/yolomux/20_sessions_popovers.css",
        "static_src/css/yolomux/30_preferences_changes.css",
        "static_src/css/yolomux/40_layout_panes_tabs.css",
        "static_src/css/yolomux/50_terminal_file_tree.css",
        "static_src/css/yolomux/60_editor_file_panels.css",
    ],
}


def repo_path(path: str | Path) -> Path:
    return REPO_ROOT / path


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def generated_header(asset: str) -> str:
    return f"/* GENERATED by tools/static_build.py from static_src/ - DO NOT EDIT {asset}; edit the partials and rebuild. */\n"


def build_asset(asset: str) -> str:
    parts = ASSETS[asset]
    return generated_header(asset) + "".join(read_text(repo_path(part)) for part in parts)


def write_asset(asset: str) -> bool:
    output_path = repo_path("static") / asset
    next_text = build_asset(asset)
    try:
        current = read_text(output_path)
    except FileNotFoundError:
        current = None
    if current == next_text:
        return False
    output_path.write_text(next_text, encoding="utf-8")
    return True


def check_asset(asset: str) -> bool:
    output_path = repo_path("static") / asset
    return read_text(output_path) == build_asset(asset)


def check_css_braces() -> None:
    """Fail the build if any CSS partial has unbalanced { } braces.

    A truncated/incomplete rule (open brace, no close) is invisible in isolation but, once the partials
    are concatenated, silently swallows the start of the NEXT partial's CSS until a stray } rebalances
    it (this exact bug shipped once — B1). Strips /* */ comments and quoted strings first so
    braces inside content/url() values don't false-positive.
    """
    for asset, parts in ASSETS.items():
        if not asset.endswith(".css"):
            continue
        for part in parts:
            text = read_text(repo_path(part))
            stripped = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
            stripped = re.sub(r"\"(?:[^\"\\]|\\.)*\"|'(?:[^'\\]|\\.)*'", "", stripped)
            opens, closes = stripped.count("{"), stripped.count("}")
            if opens != closes:
                raise BuildError(
                    f"{part}: unbalanced CSS braces ({opens} '{{' vs {closes} '}}') — a truncated or "
                    f"incomplete rule? An open rule swallows the next partial's CSS in the bundle."
                )


# Option-2 / "Durable Fix B": flag a DARK-default rule that hardcodes a theme-extreme literal color on a
# theme-sensitive property with NO body.theme-light counterpart — the root cause of every recurring
# light-mode dark-box / invisible-text bug (/19/25/28). Precision-first: only near-opaque,
# near-extreme literals (very dark backgrounds / very light text) are flagged, so vibrant brand/status
# colors that read in both themes don't false-positive. Selectors that are intentionally theme-
# independent live in LIGHT_LINT_ALLOWLIST (vetted, with a reason).
_THEME_LIGHT_SELECTORS = ("body.theme-light", "body.editor-theme-light")
_THEME_PROPS = ("background", "background-color", "color")

# Vetted intentional exceptions: a selector whose extreme literal is deliberate in BOTH themes (dark
# popovers/dialogs, terminal surfaces, the dark editor-theme swatch, fixed state badges, white-on-accent
# hovers). Reviewed 2026-06-03; AUDIT-LIGHTMODE left these dark-by-design. Anything NOT here is reported.
LIGHT_LINT_ALLOWLIST: dict[str, str] = {
    # Dark popovers / dialogs / overlays / drag ghost — intentionally dark in both themes.
    ".file-drag-image.drag-image": "drag-ghost overlay, dark by design",
    ".file-drag-icon": "drag-ghost overlay",
    ".file-drag-title": "drag-ghost overlay",
    ".terminal-context-menu": "dark popover by design (AUDIT-LIGHTMODE)",
    ".terminal-context-menu-separator": "dark popover divider",
    ".session-rename-dialog": "dark popover by design",
    ".session-rename-input": "dark popover input by design",
    ".session-rename-actions button": "dark popover button by design",
    ".file-image-preview-popover": "dark hover popover by design",
    ".modal": "dark modal by design",
    ".file-editor-dialog": "dark modal by design (AUDIT-LIGHTMODE)",
    ".file-editor-dialog-action": "dark modal button by design",
    # Terminal surfaces follow the TERMINAL theme, not the app theme.
    ".terminal-error": "terminal surface, follows the terminal theme",
    ".tmux-snapshot": "terminal snapshot surface",
    # Fixed state-badge / marker / warning colors — theme-independent (light text sits on the colored
    # badge in both themes; red attention banners are red in both).
    ".session-state-disconnected": "fixed state-badge color",
    ".session-state-working": "fixed state-badge color",
    ".session-state-needs-approval": "fixed red attention-badge color",
    ".session-state-needs-input": "fixed red attention-badge color",
    ".session-state-blocked": "fixed red attention-badge color",
    ".session-yolo-marker.locked": "fixed marker color",
    ".transport-warning": "fixed red warning-banner color",
    # White text on the accent (green) hover/focus background — reads in both themes.
    ".info-sort-button:hover": "white text on the accent hover bg",
    ".info-sort-button:focus-visible": "white text on the accent focus bg",
    ".file-explorer-close:hover": "white text on accent hover",
    ".file-explorer-close:focus-visible": "white text on accent focus",
    ".file-editor-close:hover": "white text on accent hover",
    ".file-editor-close:focus-visible": "white text on accent focus",
    ".file-explorer-panel-close:hover": "white text on accent hover",
    ".file-explorer-panel-close:focus-visible": "white text on accent focus",
    ".file-editor-panel-close:hover": "white text on accent hover",
    ".file-editor-panel-close:focus-visible": "white text on accent focus",
    # The DARK editor-theme swatch/panel is intentionally dark regardless of the app theme.
    ".file-editor-theme.theme-dark": "dark editor-theme swatch (intentional in both app themes)",
    ".file-editor-theme-panel.theme-dark": "dark editor-theme swatch",
    # Diff/conflict code surfaces are dark code blocks by design.
    ".file-editor-conflict-compare pre": "dark code/diff block by design",
    ".file-compare-line.added": "diff added-line text on the dark diff surface",
    # NOTE: .session-button-name / .session-button-dir / .markdown-body pre USED to need allowlisting
    # (their light overrides are on more-specific contextual selectors); the contextual pairing in
    # _light_covers() now recognizes those, so they no longer need entries here.
}


def _iter_css_rules(css: str):
    """Yield (selector, declaration-body) for every style rule; descend @media/@supports; skip the
    bodies of @keyframes/@font-face/@page (their inner blocks are not theme-sensitive style rules)."""
    i, n = 0, len(css)
    buf: list[str] = []
    while i < n:
        char = css[i]
        if char == "{":
            selector = "".join(buf).strip()
            buf = []
            depth, j = 1, i + 1
            while j < n and depth:
                if css[j] == "{":
                    depth += 1
                elif css[j] == "}":
                    depth -= 1
                j += 1
            body = css[i + 1:j - 1]
            if selector.startswith("@"):
                if selector.split()[0].lower() in ("@media", "@supports"):
                    yield from _iter_css_rules(body)
            else:
                yield selector, body
            i = j
            continue
        buf.append(char)
        i += 1


def _color_luminance_alpha(color: str) -> tuple[float, float] | None:
    """(relative luminance 0..1, alpha 0..1) for a #hex / rgb()/rgba() literal, else None."""
    color = color.strip().lower()
    rgb: list[int] = []
    alpha = 1.0
    hex_match = re.fullmatch(r"#([0-9a-f]{3,8})", color)
    if hex_match:
        digits = hex_match.group(1)
        if len(digits) in (3, 4):
            rgb = [int(digits[k] * 2, 16) for k in range(3)]
            if len(digits) == 4:
                alpha = int(digits[3] * 2, 16) / 255
        elif len(digits) in (6, 8):
            rgb = [int(digits[k:k + 2], 16) for k in (0, 2, 4)]
            if len(digits) == 8:
                alpha = int(digits[6:8], 16) / 255
        else:
            return None
    else:
        rgb_match = re.fullmatch(r"rgba?\(([^)]+)\)", color)
        if not rgb_match:
            return None
        parts = [p for p in re.split(r"[,\s/]+", rgb_match.group(1)) if p]
        if len(parts) < 3:
            return None
        try:
            for part in parts[:3]:
                rgb.append(int(round(float(part.rstrip("%")) * (2.55 if part.endswith("%") else 1))))
            if len(parts) >= 4:
                alpha = float(parts[3].rstrip("%")) / (100 if parts[3].endswith("%") else 1)
        except ValueError:
            return None

    def linear(value: int) -> float:
        v = max(0, min(255, value)) / 255
        return v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4

    lum = 0.2126 * linear(rgb[0]) + 0.7152 * linear(rgb[1]) + 0.0722 * linear(rgb[2])
    return lum, alpha


def _first_color_literal(value: str) -> str | None:
    """The first opaque-ish literal color in a declaration value, or None if it is themed/adaptive
    (var(), color-mix(), a gradient) or has no literal color."""
    low = value.lower()
    if "var(" in low or "color-mix(" in low or "gradient(" in low:
        return None
    hex_match = re.search(r"#[0-9a-fA-F]{3,8}\b", value)
    if hex_match:
        return hex_match.group(0)
    rgb_match = re.search(r"rgba?\([^)]+\)", value)
    if rgb_match:
        return rgb_match.group(0)
    return None


def _prop_key(prop: str) -> str:
    return "background" if prop in ("background", "background-color") else prop


def _light_covers(dark_sel: str, light_bases: list[str]) -> bool:
    """Contextual (specificity-aware) pairing: a dark rule for selector S is covered when a
    body.theme-light rule targets S itself OR S in a MORE-SPECIFIC context — i.e. some light base
    selector equals S or ends with " <S>" (a descendant suffix). Catches the common real pattern where
    the light override is scoped (e.g. dark `.session-button-name` covered by
    `body.theme-light .pane-tab:not(.active) .session-button-name`), which exact-selector pairing missed."""
    for base in light_bases:
        if base == dark_sel or base.endswith(" " + dark_sel):
            return True
    return False


def lint_light_mode_pairs() -> list[str]:
    css = "\n".join(read_text(repo_path(part)) for part in ASSETS["yolomux.css"])
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    light_by_prop: dict[str, list[str]] = {}
    dark: list[tuple[str, str, str]] = []
    for selector, body in _iter_css_rules(css):
        decls = []
        for chunk in body.split(";"):
            if ":" not in chunk:
                continue
            name, _, val = chunk.partition(":")
            name, val = name.strip().lower(), val.strip()
            if name in _THEME_PROPS:
                decls.append((name, val))
        if not decls:
            continue
        for sel in (s.strip() for s in selector.split(",") if s.strip()):
            is_light = any(token in sel for token in _THEME_LIGHT_SELECTORS)
            base = sel
            for token in _THEME_LIGHT_SELECTORS:
                base = base.replace(token + " ", "").replace(token, "").strip()
            for name, val in decls:
                if is_light:
                    light_by_prop.setdefault(_prop_key(name), []).append(base)
                else:
                    dark.append((sel, name, val))
    violations: list[str] = []
    for sel, name, val in dark:
        if sel in LIGHT_LINT_ALLOWLIST:
            continue
        color = _first_color_literal(val)
        if not color:
            continue
        measured = _color_luminance_alpha(color)
        if not measured:
            continue
        lum, alpha = measured
        if alpha < 0.6:   # translucent overlays adapt to whatever shows through; not a dark box
            continue
        is_bg = name in ("background", "background-color")
        extreme = (is_bg and lum < 0.18) or (name == "color" and lum > 0.82)
        if not extreme:
            continue
        if _light_covers(sel, light_by_prop.get(_prop_key(name), [])):
            continue   # has a body.theme-light override (exact or in a more-specific context)
        kind = "dark background" if is_bg else "near-white text"
        violations.append(f"{sel} {{ {name}: {color} }} — {kind} with no body.theme-light override")
    return violations


class BuildError(Exception):
    """Raised when the build cannot proceed (e.g. i18n key-parity failure)."""


def source_catalogs() -> dict[str, dict]:
    """All hand-authored locale catalogs from static_src/locales (excludes the generated pseudo)."""
    catalogs: dict[str, dict] = {}
    if not LOCALES_SRC.is_dir():
        return catalogs
    for path in sorted(LOCALES_SRC.glob("*.json")):
        locale = path.stem
        if locale == PSEUDO_LOCALE:
            continue
        catalogs[locale] = json.loads(read_text(path))
    return catalogs


def locale_key_errors(catalogs: dict[str, dict]) -> list[str]:
    """Every non-source catalog must have EXACTLY the en.json key set (no missing, no extra)."""
    errors: list[str] = []
    source = catalogs.get(SOURCE_LOCALE)
    if source is None:
        return errors
    source_keys = set(source)
    for locale, catalog in catalogs.items():
        if locale == SOURCE_LOCALE:
            continue
        keys = set(catalog)
        missing = sorted(source_keys - keys)
        extra = sorted(keys - source_keys)
        if missing:
            errors.append(f"{locale}.json missing keys: {', '.join(missing)}")
        if extra:
            errors.append(f"{locale}.json has unknown keys: {', '.join(extra)}")
    return errors


def pseudo_value(value: str) -> str:
    """Accent the letters (keep {tokens} intact) and pad ~40% to surface overflow / missed strings."""
    segments = re.split(r"(\{\w+\})", str(value))
    accented = "".join(seg if (seg.startswith("{") and seg.endswith("}")) else seg.translate(_PSEUDO_ACCENTS) for seg in segments)
    visible = re.sub(r"\{\w+\}", "", str(value))
    pad = "·" * max(1, round(len(visible) * 0.4))
    return f"⟦{accented}{pad}⟧"


def build_pseudo_catalog(source: dict) -> dict:
    return {key: pseudo_value(value) for key, value in source.items()}


def expected_locale_outputs() -> dict[str, str]:
    """Map of static/locales/<locale>.json -> JSON text the build should produce."""
    catalogs = source_catalogs()
    errors = locale_key_errors(catalogs)
    if errors:
        raise BuildError("i18n key-parity check failed:\n  " + "\n  ".join(errors))
    outputs: dict[str, str] = {}
    for locale, catalog in catalogs.items():
        outputs[locale] = json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    source = catalogs.get(SOURCE_LOCALE)
    if source is not None:
        outputs[PSEUDO_LOCALE] = json.dumps(build_pseudo_catalog(source), ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    return outputs


def write_locales() -> bool:
    outputs = expected_locale_outputs()
    if not outputs:
        return False
    LOCALES_OUT.mkdir(parents=True, exist_ok=True)
    changed = False
    for locale, text in outputs.items():
        path = LOCALES_OUT / f"{locale}.json"
        try:
            current = read_text(path)
        except FileNotFoundError:
            current = None
        if current != text:
            path.write_text(text, encoding="utf-8")
            changed = True
    return changed


def lint_duplicate_functions() -> list[str]:
    """Return error lines for top-level declarations made in more than one JS source file.

    The partials concatenate into one bundle sharing one scope, so a name declared in two partials lets the
    last-concatenated one win silently (AGENTS.md). this covers top-level `const`/`let`/`class`
    too, not just `function` — a duplicate const would otherwise only surface as a `node --check`
    redeclaration error, which the manual lane can miss.
    """
    js_sources = ASSETS.get("yolomux.js", [])
    name_to_files: dict[str, list[str]] = defaultdict(list)
    decl = re.compile(r"^(?:function\s+(\w+)\s*\(|(?:const|let|class)\s+(\w+)\b)")
    for part in js_sources:
        path = repo_path(part)
        try:
            text = read_text(path)
        except FileNotFoundError:
            continue
        for line in text.splitlines():
            m = decl.match(line)
            if m:
                name_to_files[m.group(1) or m.group(2)].append(str(part))
    errors = []
    for name, files in sorted(name_to_files.items()):
        if len(files) > 1:
            errors.append(f"duplicate top-level declaration '{name}' in: {', '.join(files)}")
    return errors


def lint_undefined_css_vars() -> list[str]:
    """Every `var(--x)` in the CSS bundle must resolve to a `--x:` definition (CSS) or a JS
    `setProperty('--x', …)` / inline `style="--x:…"`. a typo'd or removed token name otherwise
    degrades silently (a hover that does nothing, an invalid `font` shorthand)."""
    css = build_asset("yolomux.css")
    js = build_asset("yolomux.js")
    css_no_comments = re.sub(r"/\*.*?\*/", "", css, flags=re.DOTALL)
    defined = set(re.findall(r"(--[\w-]+)\s*:", css_no_comments))
    defined |= set(re.findall(r"setProperty\(\s*[`'\"]\s*(--[\w-]+)", js))
    defined |= set(re.findall(r"(--[\w-]+)\s*:", js))
    referenced = set(re.findall(r"var\(\s*(--[\w-]+)", css_no_comments))
    return [f"undefined CSS var {name} (referenced via var() but never defined in CSS or set from JS)"
            for name in sorted(referenced - defined)]


def check_locales() -> list[str]:
    stale: list[str] = []
    for locale, text in expected_locale_outputs().items():
        path = LOCALES_OUT / f"{locale}.json"
        try:
            current = read_text(path)
        except FileNotFoundError:
            current = None
        if current != text:
            stale.append(f"locales/{locale}.json")
    return stale


def watched_source_paths(assets: list[str]) -> list[Path]:
    """Every source file whose change should trigger a rebuild: the asset partials + locale catalogs."""
    paths: list[Path] = []
    for asset in assets:
        paths.extend(repo_path(part) for part in ASSETS[asset])
    if LOCALES_SRC.is_dir():
        paths.extend(sorted(LOCALES_SRC.glob("*.json")))
    return paths


def build_once(assets: list[str]) -> list[str]:
    check_css_braces()
    changed = [asset for asset in assets if write_asset(asset)]
    if write_locales():
        changed.append("locales")
    return changed


def watch_loop(assets: list[str], interval: float = 0.4) -> int:
    """Dev-velocity #1: rebuild on source change so the edit->reload loop drops the manual build step.
    A plain mtime poll (the build is ~36ms; no inotify dependency). A BuildError mid-edit (e.g. a
    transient locale-parity gap while typing) is printed and the watch keeps running."""
    sources = watched_source_paths(assets)
    print(f"watching {len(sources)} source files (Ctrl-C to stop); building {', '.join(assets)}", flush=True)
    try:
        changed = build_once(assets)
        print("rebuilt: " + (", ".join(changed) if changed else "(up to date)"), flush=True)
    except BuildError as exc:
        print(str(exc), file=sys.stderr, flush=True)

    def snapshot() -> dict[Path, float]:
        stamps: dict[Path, float] = {}
        for path in sources:
            try:
                stamps[path] = path.stat().st_mtime_ns
            except OSError:
                stamps[path] = 0
        return stamps

    last = snapshot()
    try:
        while True:
            time.sleep(interval)
            now = snapshot()
            if now == last:
                continue
            last = now
            try:
                changed = build_once(assets)
                if changed:
                    print("rebuilt: " + ", ".join(changed), flush=True)
            except BuildError as exc:
                print(str(exc), file=sys.stderr, flush=True)
    except KeyboardInterrupt:
        print("\nwatch stopped")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("assets", nargs="*", choices=sorted(ASSETS), help="assets to build; defaults to all")
    parser.add_argument("--check", action="store_true", help="fail if generated static files are stale")
    parser.add_argument("--watch", action="store_true", help="rebuild on source change (mtime poll) until interrupted")
    parser.add_argument("--lint-light", action="store_true", help="report dark/extreme literal colors lacking a body.theme-light override")
    args = parser.parse_args(argv)

    assets = args.assets or sorted(ASSETS)
    if args.lint_light:
        violations = lint_light_mode_pairs()
        for line in violations:
            print(line, file=sys.stderr)
        print(f"{len(violations)} light-mode pairing issue(s)", file=sys.stderr)
        return 1 if violations else 0
    if args.watch:
        return watch_loop(assets)
    try:
        if args.check:
            check_css_braces()
            stale = [asset for asset in assets if not check_asset(asset)]
            stale += check_locales()
            # the documented pre-commit gate runs the FULL lint set — duplicate top-level
            # declarations, undefined CSS vars, AND theme-light pairing (the last previously ran only under
            # --lint-light, so it was absent from --check / the CPS check list).
            lint_errors = lint_duplicate_functions() + lint_undefined_css_vars() + lint_light_mode_pairs()
            for err in lint_errors:
                print(err, file=sys.stderr)
            if stale or lint_errors:
                if stale:
                    print("stale static assets: " + ", ".join(stale), file=sys.stderr)
                return 1
            return 0

        # a plain build goes through build_once (the same path --watch uses), so an invariant
        # added there (e.g. check_css_braces) can never be skipped by the non-watch build.
        changed = build_once(assets)
        if changed:
            print("rebuilt static assets: " + ", ".join(changed))
        return 0
    except BuildError as exc:
        print(str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
