# SPDX-FileCopyrightText: Copyright (c) 2026 NV CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Build served YOLOmux static assets from ordered source partials."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]

ASSETS: dict[str, list[str]] = {
    "yolomux.js": [
        "static_src/js/yolomux/00_bootstrap_state.js",
        "static_src/js/yolomux/10_core_utils.js",
        "static_src/js/yolomux/20_layout_state.js",
        "static_src/js/yolomux/30_app_menus.js",
        "static_src/js/yolomux/40_file_explorer_files.js",
        "static_src/js/yolomux/50_editor_settings_runtime.js",
        "static_src/js/yolomux/60_popovers_tabs.js",
        "static_src/js/yolomux/70_layout_actions.js",
        "static_src/js/yolomux/80_panes_preferences.js",
        "static_src/js/yolomux/90_changes_editor.js",
        "static_src/js/yolomux/99_terminal_boot.js",
    ],
    "yolomux.css": [
        "static_src/css/yolomux/00_tokens_base.css",
        "static_src/css/yolomux/10_topbar_menus.css",
        "static_src/css/yolomux/20_sessions_popovers.css",
        "static_src/css/yolomux/30_preferences_changes.css",
        "static_src/css/yolomux/40_layout_panes_tabs.css",
        "static_src/css/yolomux/50_terminal_file_tree.css",
        "static_src/css/yolomux/60_editor_file_panels.css",
    ],
}


def repo_path(path: str | Path) -> Path:
    return REPO_ROOT / path


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def generated_header(asset: str) -> str:
    return f"/* GENERATED by tools/static_build.py from static_src/ - DO NOT EDIT {asset}; edit the partials and rebuild. */\n"


def build_asset(asset: str) -> str:
    parts = ASSETS[asset]
    return generated_header(asset) + "".join(read_text(repo_path(part)) for part in parts)


def write_asset(asset: str) -> bool:
    output_path = repo_path("static") / asset
    next_text = build_asset(asset)
    try:
        current = read_text(output_path)
    except FileNotFoundError:
        current = None
    if current == next_text:
        return False
    output_path.write_text(next_text, encoding="utf-8")
    return True


def check_asset(asset: str) -> bool:
    output_path = repo_path("static") / asset
    return read_text(output_path) == build_asset(asset)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("assets", nargs="*", choices=sorted(ASSETS), help="assets to build; defaults to all")
    parser.add_argument("--check", action="store_true", help="fail if generated static files are stale")
    args = parser.parse_args(argv)

    assets = args.assets or sorted(ASSETS)
    if args.check:
        stale = [asset for asset in assets if not check_asset(asset)]
        if stale:
            print("stale static assets: " + ", ".join(stale), file=sys.stderr)
            return 1
        return 0

    changed = [asset for asset in assets if write_asset(asset)]
    if changed:
        print("rebuilt static assets: " + ", ".join(changed))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
